Repository lab-brussels-1/group2hw, pull requests merged in 2022-03, with the labels that each got.

#6 ricardopena.md file added and people folder created PR
  package-lock.json
  people/ricardopena.md
Labels: deliverable, MD file, individual

#9 Andrii_bio
  .cspell.json
  andriivam.md
Labels: deliverable, week-2, MD file, individual

#12 Uploading my bio
  .cspell.json
  people/cristobal.md
Labels: week-2, MD file, individual

#17 Minjureadme
  people/minjujoseph.md
Labels: deliverable, MD file, individual

#23 change the directory of andriivam.md file
  people/andriivam.md
Labels: deliverable, week-2, MD file, individual

#26 create new folder pictures and files there
  .DS_Store
  imagesgroup/.DS_Store
  imagesgroup/funny.png
  imagesgroup/funny1.png
  imagesgroup/funny2.jpeg
  imagesgroup/funny3.jpeg
  imagesgroup/group_pic.jpg
  imagesgroup/group_pic2.jpg
  imagesgroup/group_pic3.jpg
  imagesgroup/group_pic4.jpg
  imagesgroup/grouppic1.jpg
  imagesgroup/hyf.png
  imagesgroup/hyf1.png
Labels: documentation, group

#31 Minjutable
  README.md
Labels: deliverable, week-2, individual

#28 created ali.md
  people/ali.md
Labels: deliverable, MD file, individual, new branch

#33 Pic update
  .cspell.json
  .vscode/settings.json
  README.md
  imagesgroup/IMG_20220220_180930.jpg
  imagesgroup/IMG_4078.jpg
  imagesgroup/Screenshot_2022-03-16_at_20.44.31.png
  imagesgroup/Screenshot_2022-03-16_at_21.13.19.png
  imagesgroup/funny.png
  imagesgroup/funny0.png
  imagesgroup/rick.jpeg
Labels: new branch

#30 created bio
  .DS_Store
  .cspell.json
  package-lock.json
  package.json
  people/swapna.md
Labels: deliverable, week-2, individual

#38 add foto for last member
  .cspell.json
  README.md
  imagesgroup/ali.jpg
Labels: new branch
